apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fl-backend-ingress
  namespace: fl-platform
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fl-backend
                port:
                  number: 80

