apiVersion: v1
kind: Service
metadata:
  name: fl-backend
  namespace: fl-platform
spec:
  selector:
    app: fl-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

