apiVersion: v1
kind: Service
metadata:
  name: fl-postgres
  namespace: fl-platform
spec:
  ports:
    - port: 5440
  selector:
    app: fl-postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fl-postgres
  namespace: fl-platform
spec:
  serviceName: "fl-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: fl-postgres
  template:
    metadata:
      labels:
        app: fl-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5440
          env:
            - name: POSTGRES_USER
              value: "fl_user"
            - name: POSTGRES_PASSWORD
              value: "fl_pass"
            - name: POSTGRES_DB
              value: "fl_db"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

